using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using OfdrwNet.Abstractions;
using OfdrwNet.Packaging;
using System.Security.Cryptography;
using System.Text;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Png;
using OfdrwNet.Layout.Element;
using OfdrwNet.Layout;
using System.Threading;
using System.Xml.Linq;
using System.IO.Compression;
using OfdrwNet.Pkg.Container;
using OfdrwNet.Models;
using OfdrwNet.Utils;
using OfdrwNet.Text;
using OfdrwNet.Font;
using RawImage = OfdrwNet.Image.RawImage;
using RawGlyphRun = OfdrwNet.Text.RawGlyphRun;
using System.Reflection;
using OfdrwNet.Core.BasicStructure.Ofd;
using OfdrwNet.Core.BasicStructure.Ofd.DocInfo;
using OfdrwNet.Core.BasicType;
using OfdrwNet.Reader;

namespace OfdrwNet
{
    /// <summary>
    /// OFD文档写入器。
    /// 对应 Java 中的 OFDDoc。
    /// </summary>
    public class OfdWriter : IDisposable, IOfdDocWriter
    {
        #region 字段
        private readonly ILogger? _logger;
        private readonly string? _outPath;
        private readonly Stream? _outStream;
        private int _maxUnitID;
        private readonly OfdContainer _ofdContainer;
        private PageLayout _pageLayout = PageLayout.A4();
        private const string DocDirectoryName = "Doc_0";
        private readonly CtDocInfo _docInfo = new();
        private string _ofdVersion = "1.1";
        private bool _autoGenerateDocId = true;
        private static readonly string DefaultCreatorName = "OfdrwNet";
        private static readonly string DefaultCreatorVersion = typeof(OfdWriter).Assembly.GetName().Version?.ToString() ?? "1.0.0";
        private bool _disposed = false;
        private readonly List<object> _streamQueue = new();
        private readonly List<OfdrwNet.Models.VirtualPage> _virtualPageList = new();
        private readonly Dictionary<string, OfdFont> _fontMap = new Dictionary<string, OfdFont>(StringComparer.OrdinalIgnoreCase);
        private readonly Dictionary<string, string> _externalFontFiles = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        private readonly List<RawImage> _rawImages = new();
        private int _imageSequence = 0; // 全局递增序号，保证图片按添加顺序输出（后面的覆盖前面的）
        private string _imageOrderingStrategy = "Sequence"; // 可通过对外扩展接口设置
        private readonly Dictionary<string, RawImage> _imageHashFirst = new(); // hash->首图
        private readonly List<RawPath> _rawPaths = new();
        private readonly List<RawAnnotation> _rawAnnotations = new();
        private int _dedupImageCount = 0;
        private List<(int PageNumber, List<object> Items)>? _pageGroups; // 预计算分页
        private string _publicResRelativePath = string.Empty;
        private string _documentResRelativePath = string.Empty;

        // RawGlyphRun / RawImage / RawPath / RawAnnotation 已移至 Models 目录
        #endregion

        #region 构造
        /// <param name="outPath">OFD输出路径，可以是目录或zip文件</param>
        /// <param name="logger">日志记录器</param>
        public OfdWriter(string outPath, ILogger? logger = null)
        {
            if (string.IsNullOrEmpty(outPath))
                throw new ArgumentException("输出路径不能为空", nameof(outPath));

            _logger = logger;
            _logger?.LogInformation("[OFDDoc] OfdWriter created for path: {Path}", outPath);
            _outPath = outPath;
            _ofdContainer = new OfdContainer(outPath);
            InitializeContainer();
        }

        /// <param name="outStream">OFD输出流</param>
        /// <param name="logger">日志记录器</param>
        public OfdWriter(Stream outStream, ILogger? logger = null)
        {
            _logger = logger;
            _logger?.LogInformation("[OFDDoc] OfdWriter created for stream.");
            _outStream = outStream;
            _ofdContainer = new OfdContainer(outStream);
            InitializeContainer();
        }


        /// <summary>
        /// 设置生成的 OFD 根节点版本号。
        /// </summary>
        public OfdWriter SetOfdVersion(string version)
        {
            if (!string.IsNullOrWhiteSpace(version))
            {
                _ofdVersion = version.Trim();
            }
            return this;
        }

        /// <summary>
        /// 配置 DocInfo 元数据。
        /// </summary>
        public OfdWriter ConfigureDocInfo(Action<CtDocInfo> configure)
        {
            configure?.Invoke(_docInfo);
            return this;
        }


        /// <summary>
        /// 控制是否自动生成 DocID。
        /// </summary>
        public OfdWriter SetAutoGenerateDocId(bool enabled)
        {
            _autoGenerateDocId = enabled;
            return this;
        }
        private void InitializeContainer()
        {
            _maxUnitID = 0;
            InitializeDocInfoDefaults();
        }

        private void InitializeDocInfoDefaults()
        {
            if (_autoGenerateDocId && string.IsNullOrWhiteSpace(_docInfo.GetDocID()))
            {
                _docInfo.RandomDocID();
            }

            if (string.IsNullOrWhiteSpace(_docInfo.GetCreator()))
            {
                _docInfo.SetCreator(DefaultCreatorName);
            }

            if (string.IsNullOrWhiteSpace(_docInfo.GetCreatorVersion()))
            {
                _docInfo.SetCreatorVersion(DefaultCreatorVersion);
            }

            if (_docInfo.GetOfdElement("CreationDate") == null)
            {
                _docInfo.SetCreationDate(DateTime.Now);
            }

            if (_docInfo.GetOfdElement("ModDate") == null)
            {
                _docInfo.SetModDate(DateTime.Now);
            }
        }

        private CtDocInfo BuildDocInfoSnapshot()
        {
            var snapshot = new CtDocInfo(new XElement(_docInfo.Element));
            EnsureDocInfoDefaults(snapshot);
            return snapshot;
        }

        private void EnsureDocInfoDefaults(CtDocInfo target)
        {
            if (_autoGenerateDocId && (target.GetOfdElement("DocID") == null || string.IsNullOrWhiteSpace(target.GetDocID())))
            {
                target.RandomDocID();
            }

            if (target.GetOfdElement("Creator") == null || string.IsNullOrWhiteSpace(target.GetCreator()))
            {
                target.SetCreator(DefaultCreatorName);
            }

            if (target.GetOfdElement("CreatorVersion") == null || string.IsNullOrWhiteSpace(target.GetCreatorVersion()))
            {
                target.SetCreatorVersion(DefaultCreatorVersion);
            }

            if (target.GetOfdElement("CreationDate") == null)
            {
                target.SetCreationDate(DateTime.Now);
            }

            if (target.GetOfdElement("ModDate") == null)
            {
                target.SetModDate(DateTime.Now);
            }
        }

        private static string IndentXml(string xml, int spaces)
        {
            if (string.IsNullOrEmpty(xml))
            {
                return string.Empty;
            }

            var indent = new string(' ', spaces);
            return indent + xml.Replace("\n", "\n" + indent);
        }
        #endregion

        #region 属性
        public PageLayout DefaultPageLayout => _pageLayout.Clone();
        public int MaxUnitID => _maxUnitID;
        public ILogger? Logger => _logger; // 接口要求
        public int DedupImageCount => _dedupImageCount;
        #endregion

        #region 添加元素
        public OfdWriter SetDefaultPageLayout(PageLayout pageLayout)
        {
            if (pageLayout != null)
                _pageLayout = pageLayout;
            return this;
        }

        public OfdWriter Add(Div item)
        {
            if (_streamQueue.Contains(item))
                throw new ArgumentException("元素已经存在");
            _streamQueue.Add(item);
            return this;
        }

        public OfdWriter Add(Paragraph paragraph)
        {
            if (_streamQueue.Contains(paragraph))
                throw new ArgumentException("元素已经存在");
            _streamQueue.Add(paragraph);
            return this;
        }

        public OfdWriter AddExternalEmbeddedFont(string fontName, string fontFilePath)
        {
            if (string.IsNullOrWhiteSpace(fontName))
                throw new ArgumentNullException(nameof(fontName));
            if (string.IsNullOrWhiteSpace(fontFilePath) || !File.Exists(fontFilePath))
                throw new FileNotFoundException("字体文件不存在", fontFilePath);
            _externalFontFiles[fontName] = fontFilePath;
            return this;
        }
        IOfdDocWriter IOfdDocWriter.AddExternalEmbeddedFont(string fontName, string fontFilePath) => AddExternalEmbeddedFont(fontName, fontFilePath);

        public OfdWriter AddRawTextGlyphRun(string fontName, double fontSizeMm, double originX, double originY, double width, double height, string text, double[]? deltaX = null, double[]? deltaY = null, int[]? glyphs = null, int page = 1, double[]? ctm = null, double? baselineY = null, double[]? charStarts = null, double[]? charAdvances = null)
        {
            var run = new RawGlyphRun
            {
                FontName = string.IsNullOrWhiteSpace(fontName) ? "SimSun" : fontName,
                FontSizeMm = fontSizeMm,
                X = originX,
                Y = originY,
                Width = width,
                Height = height,
                Text = text ?? string.Empty,
                DeltaX = deltaX,
                DeltaY = deltaY,
                Glyphs = glyphs,
                Page = page < 1 ? 1 : page,
                CTM = NormalizeCtm(ctm),
                BaselineY = baselineY,
                CharStarts = charStarts,
                CharAdvances = charAdvances
            };
            _streamQueue.Add(run);
            return this;
        }
        IOfdDocWriter IOfdDocWriter.AddRawTextGlyphRun(string fontName, double fontSizeMm, double originX, double originY, double width, double height, string text, double[]? deltaX, double[]? deltaY, int[]? glyphs, int page, double[]? ctm, double? baselineY, double[]? charStarts, double[]? charAdvances)
            => AddRawTextGlyphRun(fontName, fontSizeMm, originX, originY, width, height, text, deltaX, deltaY, glyphs, page, ctm, baselineY, charStarts, charAdvances);

        public OfdWriter AddRawImage(string format, double x, double y, double width, double height, byte[] data, int page = 1, double[]? ctm = null)
        {
            if (data == null || data.Length == 0)
            {
                _logger?.LogDebug("[OFDDoc][Image] Skip empty image data Page={Page}", page);
                return this;
            }
            string hash;
            try
            {
                using var sha = SHA256.Create();
                hash = Convert.ToHexString(sha.ComputeHash(data));
            }
            catch { hash = Guid.NewGuid().ToString("N"); }
            bool first = !_imageHashFirst.ContainsKey(hash);
            if (!first)
                _dedupImageCount++;
            var img = new RawImage
            {
                Format = string.IsNullOrWhiteSpace(format) ? "PNG" : format.ToUpperInvariant(),
                X = x,
                Y = y < 0 ? 0 : y,
                Width = width <= 0 ? 1 : width,
                Height = height <= 0 ? 1 : height,
                Data = first ? data : Array.Empty<byte>(),
                Page = page < 1 ? 1 : page,
                Hash = hash,
                IsFirstResource = first,
                CTM = NormalizeCtm(ctm),
                Sequence = System.Threading.Interlocked.Increment(ref _imageSequence),
                Z = 0
            };
            _rawImages.Add(img);
            if (first)
            {
                _imageHashFirst[hash] = img;
                _logger?.LogDebug("[OFDDoc][Image] Page={Page} NewImage Hash={Hash} {W}x{H}mm Format={Fmt} Z={Z}", img.Page, hash[..Math.Min(12, hash.Length)], img.Width.ToString("0.##"), img.Height.ToString("0.##"), img.Format, img.Z);
            }
            else
            {
                _logger?.LogDebug("[OFDDoc][Image] Page={Page} DupImage Hash={Hash} Z={Z}", img.Page, hash[..Math.Min(12, hash.Length)], img.Z);
            }
            return this;
        }


        public OfdWriter AddImage(OfdImage image)
        {
            if (image == null)
                return this;
            return AddRawImage(image.Format, image.X, image.Y, image.Width, image.Height, image.ImageData, image.Page, image.CTM);
        }


        public OfdWriter AddText(OfdText text)
        {
            if (text == null || string.IsNullOrEmpty(text.Text))
                return this;
            return AddRawTextGlyphRun(text.FontFamily, text.FontSize, text.X, text.Y, text.Width, text.Height, text.Text, text.DeltaX?.Select(d => (double)d).ToArray(), null, text.Glyphs, text.Page, text.CTM, text.BaselineY, text.CharStarts, text.CharAdvances);
        }

        /// <summary>
        /// 添加路径到OFD文档
        /// </summary>
        /// <param name="path">OFD路径对象</param>
        /// <returns>OfdWriter实例，用于链式调用</returns>
        public OfdWriter AddPath(OfdPath path)
        {
            if (path == null || string.IsNullOrEmpty(path.PathData))
                return this;
            _rawPaths.Add(new RawPath
            {
                PathData = path.PathData,
                X = path.X,
                Y = path.Y,
                Width = path.Width,
                Height = path.Height,
                Page = path.Page,
                CTM = path.CTM,
                StrokeColor = path.StrokeColor,
                FillColor = path.FillColor,
                DashPattern = path.DashPattern?.Length > 0 ? path.DashPattern.ToArray() : null,
                LineWidth = path.LineWidth,
                Stroke = path.Stroke,
                Fill = path.Fill
            });
            return this;
        }

        /// <summary>
        /// 添加注释到OFD文档
        /// </summary>
        /// <param name="annotation">注释对象</param>
        /// <param name="page">页码，从1开始</param>
        /// <returns>OfdWriter实例，用于链式调用</returns>
        public OfdWriter AddAnnotation(object annotation, int page = 1)
        {
            if (annotation == null)
                return this;
            _rawAnnotations.Add(new RawAnnotation
            {
                Annotation = annotation,
                Page = page < 1 ? 1 : page
            });
            return this;
        }
        IOfdDocWriter IOfdDocWriter.AddAnnotation(object annotation, int page) => AddAnnotation(annotation, page);

        /// <summary>
        /// 添加表单字段到OFD文档
        /// </summary>
        /// <param name="formField">表单字段对象</param>
        /// <returns>OfdWriter实例，用于链式调用</returns>
        public OfdWriter AddFormField(object formField)
        {
            // 暂时只是记录表单字段，稍后实现完整的表单处理
            if (formField == null)
                return this;
            _logger?.LogDebug("[OFDDoc][Form] 添加表单字段: {Type}", formField.GetType().Name);
            return this;
        }

        #region 辅助 - CTM
        private static double[]? NormalizeCtm(double[]? ctm) => CtmUtil.Normalize(ctm);
        #endregion

        #region ID
        public int GetNextID() => Interlocked.Increment(ref _maxUnitID);
        #endregion

        #region 生成/关闭
        public async Task CloseAsync()
        {
            if (_disposed)
                return;
            try
            {
                if (_streamQueue.Count > 0 || _rawImages.Count > 0)
                {
                    // Simplified: treat all raw additions as a single virtual page for now
                    var vp = new OfdrwNet.Models.VirtualPage(_pageLayout);
                    foreach (var item in _streamQueue)
                    {
                        // This part needs a proper layout engine to place elements.
                        // For now, we just add them to a virtual page.
                    }
                    _virtualPageList.Add(vp);
                }

                if (_virtualPageList.Count == 0)
                    _virtualPageList.Add(new OfdrwNet.Models.VirtualPage(_pageLayout));

                await GenerateDocumentAsync();
            }
            finally
            {
                _disposed = true;
                _ofdContainer.Dispose();
            }
        }

        private async Task GenerateDocumentAsync()
        {
            if (!string.IsNullOrEmpty(_outPath))
            {
                await GenerateOfdContentAsync(_outPath);
            }
            else if (_outStream != null)
            {
                await GenerateOfdContentAsync(_outStream);
            }
            else
                throw new InvalidOperationException("未设置输出");
        }

        private async Task GenerateOfdContentAsync(string outputPath)
        {
            var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            try
            {
                await CreateOfdStructureAsync(tempDir);
                if (File.Exists(outputPath))
                    File.Delete(outputPath);

                // 检查输出路径是目录还是文件
                if (Directory.Exists(outputPath) || Path.GetExtension(outputPath).ToLowerInvariant() != ".ofd")
                {
                    // 如果是目录或没有.ofd扩展名，则复制文件到目录
                    if (!Directory.Exists(outputPath))
                    {
                        Directory.CreateDirectory(outputPath);
                    }
                    // 复制所有文件
                    foreach (var file in Directory.GetFiles(tempDir, "*", SearchOption.AllDirectories))
                    {
                        var relativePath = Path.GetRelativePath(tempDir, file);
                        var destFile = Path.Combine(outputPath, relativePath);
                        var destDir = Path.GetDirectoryName(destFile);
                        if (!string.IsNullOrEmpty(destDir) && !Directory.Exists(destDir))
                            Directory.CreateDirectory(destDir);
                        File.Copy(file, destFile, true);
                    }
                    _logger?.LogInformation("[OFDDoc][GenerateOfdContentAsync] OFD文件已复制到目录: {OutputPath}", outputPath);
                }
                else
                {
                    // 如果是.ofd文件，则创建ZIP
                    ZipFile.CreateFromDirectory(tempDir, outputPath);
                    _logger?.LogInformation("[OFDDoc][GenerateOfdContentAsync] OFD文件已创建: {OutputPath}", outputPath);
                }
            }
            finally { if (Directory.Exists(tempDir)) Directory.Delete(tempDir, true); }
        }

        private async Task GenerateOfdContentAsync(Stream outputStream)
        {
            var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            try
            {
                await CreateOfdStructureAsync(tempDir);
                using var archive = new ZipArchive(outputStream, ZipArchiveMode.Create, true);
                foreach (var file in Directory.GetFiles(tempDir, "*", SearchOption.AllDirectories))
                {
                    var entryName = Path.GetRelativePath(tempDir, file).Replace('\\', '/');
                    var entry = archive.CreateEntry(entryName);
                    using var entryStream = entry.Open();
                    using var fileStream = File.OpenRead(file);
                    await fileStream.CopyToAsync(entryStream);
                }
            }
            finally { if (Directory.Exists(tempDir)) Directory.Delete(tempDir, true); }
        }

        private async Task CreateOfdStructureAsync(string baseDir)
        {
            if (_pageGroups == null)
            {
                var pgBuilder = new OfdrwNet.Services.PageGroupBuilder(_logger);
                _pageGroups = pgBuilder.Build(_streamQueue, _virtualPageList, _rawImages, _rawPaths);
            }
            _logger?.LogDebug("[OFD][CreateStructure] Pages={PageCount}", _pageGroups?.Count);
            // 使用 Core 中的模型类构建 OFD.xml 而不是直接字符串拼接
            // 引用: OfdrwNet.Core.BasicStructure.Ofd.OFD / DocBody / CtDocInfo 以及 BasicType.StLoc
            var docInfoSnapshot = BuildDocInfoSnapshot();
            try
            {
                var docBody = new DocBody()
                    .SetDocInfo(docInfoSnapshot)
                    .SetDocRoot(new StLoc($"{DocDirectoryName}/Document.xml"));

                var ofd = new OFD(docBody).SetVersion(_ofdVersion);
                var ofdXml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" + ofd.ToXml();
                await FileUtil.WriteTextFileUtf8LfAsync(Path.Combine(baseDir, "OFD.xml"), ofdXml);
            }
            catch (Exception ex)
            {
                _logger?.LogError(ex, "[OFDDoc][CreateOfdStructureAsync] 构建 OFD.xml 失败，回退到最小结构");
                var fallbackInfo = BuildDocInfoSnapshot();
                var fallbackBuilder = new StringBuilder();
                fallbackBuilder.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                fallbackBuilder.AppendLine($"<ofd:OFD xmlns:ofd=\"http://www.ofdspec.org/2016\" DocType=\"OFD\" Version=\"{_ofdVersion}\">");
                fallbackBuilder.AppendLine("  <ofd:DocBody>");
                fallbackBuilder.AppendLine(IndentXml(fallbackInfo.ToXml(), 4));
                fallbackBuilder.AppendLine($"    <ofd:DocRoot>{DocDirectoryName}/Document.xml</ofd:DocRoot>");
                fallbackBuilder.AppendLine("  </ofd:DocBody>");
                fallbackBuilder.AppendLine("</ofd:OFD>");
                await FileUtil.WriteTextFileUtf8LfAsync(Path.Combine(baseDir, "OFD.xml"), fallbackBuilder.ToString());
            }
            var docDir = Path.Combine(baseDir, DocDirectoryName);
            Directory.CreateDirectory(docDir);
            _logger?.LogInformation("[OFDDoc][CreateOfdStructureAsync] 准备调用GenerateResourcesAsync DocDir={DocDir}", docDir);
            await GenerateResourcesAsync(docDir);
            _logger?.LogInformation("[OFDDoc][CreateOfdStructureAsync] GenerateResourcesAsync调用完成");
            var pagesDir = Path.Combine(docDir, "Pages");
            Directory.CreateDirectory(pagesDir);
            // 先生成页面文件（页面和内容会为对象分配ID），再生成 Document.xml，以便 MaxUnitID 能覆盖所有ID
            await GeneratePageFilesAsync(pagesDir);
            var documentXml = await GenerateDocumentXmlAsync();
            await FileUtil.WriteTextFileUtf8LfAsync(Path.Combine(docDir, "Document.xml"), documentXml);
            _logger?.LogInformation("[OFDDoc][CreateOfdStructureAsync] 准备调用PostGenerationFixAsync");
            await PostGenerationFixAsync(baseDir);
            _logger?.LogInformation("[OFDDoc][CreateOfdStructureAsync] PostGenerationFixAsync调用完成");
        }

        private async Task<string> GenerateDocumentXmlAsync()
        {
            if (_pageGroups == null)
            {
                var pgBuilder = new OfdrwNet.Services.PageGroupBuilder(_logger);
                _pageGroups = pgBuilder.Build(_streamQueue, _virtualPageList, _rawImages, _rawPaths);
            }
            if (_pageGroups == null)
                _pageGroups = new List<(int PageNumber, List<object> Items)>();
            // 使用 Core 模型构建 Document.xml
            // 1. 创建 CommonData，包括 MaxUnitID、PageArea、公共/文档资源引用
            var commonData = new OfdrwNet.Core.BasicStructure.Doc.CtCommonData()
                .SetMaxUnitId((long)_maxUnitID)
                .SetPageArea(new OfdrwNet.Core.BasicStructure.Doc.CtPageArea(0, 0, _pageLayout.Width, _pageLayout.Height));
            if (!string.IsNullOrEmpty(_publicResRelativePath))
            {
                commonData.AddPublicRes(new OfdrwNet.Core.BasicType.StLoc(_publicResRelativePath));
            }
            if (!string.IsNullOrEmpty(_documentResRelativePath))
            {
                commonData.AddDocumentRes(new OfdrwNet.Core.BasicType.StLoc(_documentResRelativePath));
            }

            // 2. 创建 Pages 集合，并为每页分配 ID（与原先逻辑一致：调用 GetNextID）
            var orderedPages = _pageGroups.OrderBy(p => p.PageNumber).ToList();
            var pagesElement = new OfdrwNet.Core.BasicStructure.PageTree.Pages();
            foreach (var pg in orderedPages)
            {
                var pid = GetNextID();
                var pageIndex = Math.Max(pg.PageNumber - 1, 0);
                pagesElement.AddPage(new OfdrwNet.Core.BasicStructure.PageTree.Page(pid, $"Pages/Page_{pageIndex}/Content.xml"));
            }

            // 注意：上面分配页面ID时调用了 GetNextID 可能会提升 _maxUnitID，需要更新 CommonData 的 MaxUnitID
            if (_maxUnitID < 0)
                _maxUnitID = 0; // 防御性
            // 重新覆盖最新 MaxUnitID
            commonData.SetMaxUnitId((long)_maxUnitID);

            // 3. 创建 Document 根并附加 CommonData 和 Pages
            var document = new OfdrwNet.Core.BasicStructure.Doc.Document()
                .SetCommonData(commonData)
                .SetPages(pagesElement);

            // 4. 输出 XML 字符串（添加 XML 声明）
            var xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" + document.ToXml();
            await Task.CompletedTask;
            return xml;
        }

        private async Task GeneratePageFilesAsync(string pagesDir)
        {
            if (_fontMap.Count == 0)
            {
                var fontRegistry = new OfdrwNet.Font.OfdFontRegistry(_logger);
                foreach (var kv in fontRegistry.Build(_externalFontFiles, _streamQueue))
                    _fontMap[kv.Key] = kv.Value;
            }
            if (_pageGroups == null)
            {
                var pgBuilder = new OfdrwNet.Services.PageGroupBuilder(_logger);
                _pageGroups = pgBuilder.Build(_streamQueue, _virtualPageList, _rawImages, _rawPaths);
            }
            var writer = new OfdrwNet.Services.PageContentWriter(_logger);
            foreach (var pg in _pageGroups)
            {
                var pageIndex = Math.Max(pg.PageNumber - 1, 0);
                await writer.WritePageAsync(pagesDir, pg.PageNumber, pageIndex, pg.Items, _rawImages, _rawPaths, _fontMap, _imageOrderingStrategy, GetNextID, _pageLayout.Width, _pageLayout.Height);
            }
        }

        private void BuildFontMap()
        {
            _fontMap.Clear();
            int id = 1;
            var fontNames = _streamQueue.OfType<RawGlyphRun>().Select(rg => rg.FontName)
                                      .Concat(_externalFontFiles.Keys)
                                      .Distinct(StringComparer.OrdinalIgnoreCase);

            foreach (var name in fontNames)
            {
                if (!_fontMap.ContainsKey(name))
                {
                    _fontMap[name] = new OfdFont(id++, name, name);
                }
            }
            if (_fontMap.Count == 0)
                _fontMap["SimSun"] = new OfdFont(1, "SimSun", "宋体");
        }

        private async Task GenerateResourcesAsync(string docDir)
        {
            BuildFontMap();
            var generator = new OfdrwNet.Services.ResourceGenerator(_logger);
            var result = await generator.GenerateAsync(docDir, _fontMap, _externalFontFiles, _rawImages);
            _publicResRelativePath = result.PublicResRelativePath;
            _documentResRelativePath = result.DocumentResRelativePath;
            _maxUnitID = Math.Max(_maxUnitID, result.MaxUnitIdAfterResources);
        }

        private async Task PostGenerationFixAsync(string baseDir)
        {
            // Simplified, as the new generation logic should be more correct.
            await Task.CompletedTask;
        }

        #endregion
        public void Dispose()
        {
            if (!_disposed)
            {
                _ofdContainer?.Dispose();
                _disposed = true;
            }
        }

    }

    #endregion

    /// <summary>
    /// 兼容旧命名的 OFDDoc（保留以减少外部迁移成本）。
    /// </summary>
    [Obsolete("Use OfdWriter instead. This shim will be removed in future releases.")]
    public class OFDDoc : OfdWriter
    {
        /// <summary>创建基于输出目录的 OFDDoc。</summary>
        public OFDDoc(string outPath, ILogger? logger = null) : base(outPath, logger) { }
        /// <summary>创建基于输出流的 OFDDoc。</summary>
        public OFDDoc(Stream outStream, ILogger? logger = null) : base(outStream, logger) { }
    }
}
